name: 'Instellar PAKman'
author: 'Zack Siri'
branding:
  icon: 'package'
  color: 'purple'
description: 'Builds project into alpine package to be deployed using instellar.app'
inputs:
  alpine:
    description: |
      Alpine linux version to use (edge | v3.18 | v3.17 | v3.16 | v3.15)
    required: true
runs:
  using: composite
  steps:
    - name: Setup Alpine
      uses: jirutka/setup-alpine@v1
      with:
        branch: ${{ inputs.alpine }}
        packages: |
          zip
          tar
          sudo
          cmake
          elixir
          coreutils
          alpine-sdk

    - name: Add Runner Permission
      run: sudo addgroup runner abuild
      shell: alpine.sh {0}

    - name: Cache Pakman
      id: cache-pakman
      uses: actions/cache@v3
      with:
        path: ~/.mix
        key: ${{ runner.arch }}-alpine-${{ inputs.alpine }}-pakman

    - name: Install Pakman
      if: steps.cache-pakman.outputs.cache-hit != 'true'
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix escript.install hex pakman 8.0.0 --force
      shell: alpine.sh {0}
      env:
        MIX_ENV: prod
