name: 'Instellar PAKman'
author: 'Zack Siri'
description: 'Builds project into alpine package to be deployed using instellar.app'
inputs:
  command:
    description: 'command to run'
    required: true
  archive:
    description: 'archive path'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - --command
    - ${{inputs.command}}
    - --archive
    - ${{inputs.archive}}
branding:
  icon: 'package'
  color: 'purple'
